import type { AnimeWithCovers } from '@/types/anime';

/**
 * Fake anime data for development (matching Supabase schema)
 * This will be replaced with real Supabase data
 */
export const fakeAnimeData: AnimeWithCovers[] = [
  {
    id: '1',
    mal_id: 1,
    title: 'Dragon Chronicles',
    title_english: 'Dragon Chronicles',
    title_japanese: 'ドラゴン・クロニクルズ',
    synopsis:
      'A young warrior discovers their hidden power to control dragons and must save their kingdom from an ancient evil that threatens to destroy everything they hold dear.',
    type: 'TV',
    status: 'Finished',
    episodes: 24,
    duration: 24,
    aired_from: '2023-01-01',
    aired_to: '2023-06-30',
    season: 'Winter',
    year: 2023,
    score: 8.5,
    scored_by: 15000,
    rank: 100,
    popularity: 500,
    rating: 'PG-13',
    source: 'Manga',
    studios: ['Studio Bones'],
    producers: ['Aniplex'],
    trailer: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    covers: [
      {
        id: '1-1',
        anime_id: '1',
        url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&h=700&fit=crop',
        size: 'large',
        width: 500,
        height: 700,
        is_primary: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: '2',
    mal_id: 2,
    title: 'Cyber City 2099',
    title_english: 'Cyber City 2099',
    title_japanese: 'サイバーシティ2099',
    synopsis:
      'In a neon-lit future metropolis, a hacker uncovers a conspiracy that could change the fate of humanity forever. Action-packed cyberpunk thriller with stunning visuals.',
    type: 'TV',
    status: 'Airing',
    episodes: 12,
    duration: 24,
    aired_from: '2024-10-01',
    aired_to: null,
    season: 'Fall',
    year: 2024,
    score: 9.1,
    scored_by: 25000,
    rank: 20,
    popularity: 100,
    rating: 'R-17+',
    source: 'Original',
    studios: ['Trigger', 'MAPPA'],
    producers: ['Netflix'],
    trailer: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    covers: [
      {
        id: '2-1',
        anime_id: '2',
        url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&h=700&fit=crop',
        size: 'large',
        width: 500,
        height: 700,
        is_primary: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: '3',
    mal_id: 3,
    title: 'Magical Academy',
    title_english: 'Magical Academy',
    title_japanese: 'マジカル・アカデミー',
    synopsis:
      "Students at an elite magic school compete in tournaments while uncovering dark secrets about their institution's past. Friendship, rivalry, and supernatural powers collide.",
    type: 'TV',
    status: 'Finished',
    episodes: 36,
    duration: 24,
    aired_from: '2022-04-01',
    aired_to: '2023-03-31',
    season: 'Spring',
    year: 2022,
    score: 7.8,
    scored_by: 12000,
    rank: 300,
    popularity: 800,
    rating: 'PG-13',
    source: 'Light novel',
    studios: ['A-1 Pictures'],
    producers: ['Aniplex', 'Crunchyroll'],
    trailer: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    covers: [
      {
        id: '3-1',
        anime_id: '3',
        url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=500&h=700&fit=crop',
        size: 'large',
        width: 500,
        height: 700,
        is_primary: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
];
